name: "Test Basic Action with Inputs"

on:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Basic Print Action
        uses: ./.github/actions/basic-action
        with:
          input1: "Hello from Input 1"
          input2: "This is Input 2"
